name: Go Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.4'

      - name: Check code formatting
        uses: Jerome1337/gofmt-action@v1.0.5

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1

      - name: Test
        run: go test -v ./...
